#!/bin/sh
if [ -e "$JAVA_HOME"/bin/javac ]
then
  if [ $( uname | cut -c1-6 ) = CYGWIN ]
  then
    # for cygwin:
    "$JAVA_HOME"/bin/java -DJAVA_HOME="$JAVA_HOME" -cp "$JAVA_HOME"\\lib\\tools.jar\;lib\\ant.jar\;lib\\ant-launcher.jar org.apache.tools.ant.Main $1
  else
    "$JAVA_HOME"/bin/java -DJAVA_HOME="$JAVA_HOME" -cp "$JAVA_HOME"/lib/tools.jar:lib/ant.jar:lib/ant-launcher.jar org.apache.tools.ant.Main $1
  fi
else
  echo "You must set the JAVA_HOME environment variable"
  echo "  For example:  export JAVA_HOME=/usr/local/jdk1.5"
  echo "  Or under Cygwin:  export JAVA_HOME=\"c:\\\\Program Files\\\\Java\\\\jdk1.5.0\""
  exit 1
fi

#cd src/wilmapye
#omniidl -bpython ../corba/WilmaChat.idl

