#!/bin/sh
if [ -e $JAVA_HOME/bin/javac ]
then
  if [ x$OS = xWindows_NT ]
  then
    # for cygwin:
    java -DJAVA_HOME=$JAVA_HOME -cp $JAVA_HOME\\lib\\tools.jar\;lib\\ant.jar\;lib\\jaxp.jar\;lib\\crimson.jar\;lib\\xalan.jar org.apache.tools.ant.Main $1
  else
    java -DJAVA_HOME=$JAVA_HOME -cp $JAVA_HOME/lib/tools.jar:lib/ant.jar:lib/jaxp.jar:lib/crimson.jar:lib/xalan.jar org.apache.tools.ant.Main $1
  fi
else
  echo "You must set the JAVA_HOME environment variable"
  echo "  For example:  export JAVA_HOME=/usr/local/jdk1.3.1"
  echo "  Or on Debian:  export JAVA_HOME=/usr/lib/j2sdk1.3.1"
  echo "  Or under Cygwin:  export JAVA_HOME=c:\\jdk1.3.1"
  exit 1
fi

#cd src/wilmapye
#omniidl -bpython ../corba/WilmaChat.idl

