/* Generated By:JavaCC: Do not edit this line. GMLParserConstants.java */
package org.wilmascope.gmlparser;

public interface GMLParserConstants {

  int EOF = 0;
  int GRAPH = 14;
  int VERSION = 15;
  int DIRECTED = 16;
  int NAME = 17;
  int NODE = 18;
  int EDGE = 19;
  int ID = 20;
  int LABEL = 21;
  int SOURCE = 22;
  int TARGET = 23;
  int NUM = 24;
  int DEC = 25;
  int CTLSTRING = 26;

  int DEFAULT = 0;
  int IN_IGNORABLE = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\\\"",
    "\"Line\"",
    "\"LabelGraphics\"",
    "\"node_style\"",
    "\"edge_style\"",
    "\"style\"",
    "\"[\"",
    "\"]\"",
    "<token of kind 13>",
    "\"graph\"",
    "\"version\"",
    "\"directed\"",
    "\"name\"",
    "\"node\"",
    "\"edge\"",
    "\"id\"",
    "\"label\"",
    "\"source\"",
    "\"target\"",
    "<NUM>",
    "<DEC>",
    "<CTLSTRING>",
    "\"[\"",
    "\"]\"",
    "\"graphics\"",
    "\"x\"",
    "\"y\"",
    "\"w\"",
    "\"h\"",
    "\"type\"",
    "\"arrow\"",
    "\"capstyle\"",
  };

}
