/* Generated By:JavaCC: Do not edit this line. DotParserConstants.java */
package org.wilmascope.dotparser;

public interface DotParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int GRAPH = 9;
  int DIGRAPH = 10;
  int NODE = 11;
  int LABEL = 12;
  int POS = 13;
  int SHAPE = 14;
  int BB = 15;
  int WIDTH = 16;
  int WEIGHT = 17;
  int HEIGHT = 18;
  int CONCENTRATE = 19;
  int LAYER = 20;
  int LAYERS = 21;
  int MINLEN = 22;
  int ID = 23;
  int NUM = 24;
  int DEC = 25;
  int IGNOREPARAMETERS = 28;

  int DEFAULT = 0;
  int NODEPARAMETERS = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\\\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"graph\"",
    "\"digraph\"",
    "\"node\"",
    "\"label\"",
    "\"pos\"",
    "\"shape\"",
    "\"bb\"",
    "\"width\"",
    "\"weight\"",
    "\"height\"",
    "\"concentrate\"",
    "\"layer\"",
    "\"layers\"",
    "\"minlen\"",
    "<ID>",
    "<NUM>",
    "<DEC>",
    "\" \"",
    "\"\\t\"",
    "<IGNOREPARAMETERS>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"[\"",
    "\"=true\"",
    "\"=\"",
    "\"\\\"\"",
    "\":\"",
    "\",\"",
    "\"]\"",
    "\".\"",
    "\"->\"",
    "\"e,\"",
    "\"s,\"",
  };

}
